### ISSUE TITLE
Gebruikersonderzoek inwoners

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/Innovatie-ID-wallet#38]
Gebruikersonderzoek: inwoners

obv prototype evalueren met gebruikers en bredere interviews houden ->ink
afspraken voor testen in sprint 3 -> Nijmegen, Innovalor

- [x] formulier voor tekenen ontvangst vergoeding onkosten
- [x] mail versturen naar inwoners/deelnemers voor 29-11

**Comment by SaskiaJanssen** [comment]
Link naar voorbereiding enquete vragen: https://irvnnijmegen.sharepoint.com/:w:/r/sites/P-ID-walletinnovatiebudget/Shared%20Documents/General/Projectdocumenten/C.%20Projectactiviteiten/Gebruikersonderzoek/Vragen%20enquete%20Yivi.docx?d=wa951da391ece42a69a38de63ac1151c2&csf=1&web=1&e=nVQpro
