### ISSUE TITLE
gebruikers voor de meedoenregeling aanschrijven

### ISSUE THREAD

**Issue by wvdeeckhout** [GemeenteNijmegen/Innovatie-ID-wallet#79]
Vanuit de enqueteresultaten bekijken of er medewerkers zijn die onder de doelgroep vallen. Er zijn 24 inwoners die onder de doelgroep vallen

- [x] Nijmegen levert lijst van inwoner aan bij INK
- [ ] afstemmen of INK of Nijmegen deze gebruikers aanschrijft.

**Comment by SaskiaJanssen** [comment]
Marieke Selten gemaild mbt resultatenoverzicht  sturen van de enquete

**Comment by wvdeeckhout** [comment]
Het aanleveren van de lijst is in sprint 3 gedaan. Het uitnodigen gebeurd in de volgende sprint.

**Comment by wvdeeckhout** [comment]
2 mensen Nederlandse taal niet beheersen
2 mensen wel Nederlandste taal en computervaardig

**Comment by wvdeeckhout** [comment]
4 deelnemers aangewezen door INK hebben een mail gekregen met daarin de vraag om te reageren wanneer ze kunnen.
